"""create items table

Revision ID: 9fe7e08524d7
Revises: 
Create Date: 2026-09-28 21:20:15.379802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe7e08524d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_key', sa.String(), nullable=False),
    sa.Column('quantity_base', sa.Float(), nullable=False),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('display_unit', sa.String(), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('quantity_base >= 0', name='ck_items_quantity_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_key')
    )
    op.create_index('ix_items_expires_on', 'items', ['expires_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_expires_on', table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
